parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

# doctrine:
#     dbal:
#         url: '%env(resolve:DATABASE_URL)%'

#         # IMPORTANT: You MUST configure your server version,
#         # either here or in the DATABASE_URL env var (see .env file)
#         #server_version: '5.7'
#     orm:
#         auto_generate_proxy_classes: true
#         naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
#         auto_mapping: true
#         mappings:
#             App:
#                 is_bundle: false
#                 type: annotation
#                 dir: '%kernel.project_dir%/src/Entity'
#                 prefix: 'App\Entity'
#                 alias: App
doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    connections:
        default:
            server: '%env(resolve:MONGODB_URL)%'
            options:
                username: '%env(resolve:MONGODB_DB_USER)%'
                password: '%env(resolve:MONGODB_DB_PWD)%'
    default_database: '%env(resolve:MONGODB_DB)%'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: 'App\Document'
                    alias: App
