knp_snappy:
    pdf:
        enabled:    true
        # binary:     '%env(WKHTMLTOPDF_PATH)%'
        binary:     '%kernel.root_dir%/../vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'
        options:
            - { name: 'viewport-size', value: ‘1920x1080’ }
            - { name: 'page-size', value: 'A4' }
    image:
        enabled:    true
        binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        options:    []
